### ISSUE TITLE
Метод containsGame возвращает false для добавленной в store игры

### ISSUE THREAD

**Issue by Mezis4** [MeziTest/QA-51_TeamDiplom#2]
# Описание
Метод `containsGame` в классе `GameStore` возвращает `false` при наличии игры в `store`
## Локация дефекта
https://github.com/MeziTest/QA-51_TeamDiplom/blob/7c8cf037ffcd6170e4de79d97c7c0c8d80e2cbb8/src/main/java/ru/netology/GameStore.java#L32

# Шаги воспроизведения
1. Открыть [код программы в ветке gamestore](https://github.com/MeziTest/QA-51_TeamDiplom/tree/gamestore) в IDEA и открыть `GameStoreTest`
1. Найти тест `shouldTrueIfGameExist`
1. Для `Game` выставить: значение параметра `title` "Нетология Баттл Онлайн" 
1. Выставить значение параметра `genre` "Аркады"
1. Выставить значение параметра `store` oneGameStore
1. Запустить тест
1. Посмотреть в значение actual

*Ожидаемый результат:* В консоли в строке actual отображается значение `true`
*Фактический результат:* В консоли в строке actual отображается значение `false`

# Скриншот
![метод contains (1)](https://user-images.githubusercontent.com/117623022/215490327-bc43ca07-1513-45b4-b985-af7dbeea97ed.png)
![метод contains](https://user-images.githubusercontent.com/117623022/215490264-89f60ce8-a44b-4416-891f-460f00378a48.png)

# Комментарии
В тест-кейсах, содержащих метод `containsGame` , возникает такая же проблема (например: `shouldAddNewGameInEmptyStore`, `shouldAddNewGameInOneGameStore`, `shouldAddNewGameInSeveralGameStore`)

# Окружение
* **Операционная система:** Windows 11, версия 21H2
* **IDE:** IntelliJ IDEA 2022.2.4 (Community Edition)
* **Java:** OpenJDK 11

**Comment by andrewturchak78** [comment]
The bug was fixed.
