### ISSUE TITLE
Метод publishGame повторно добавляет игру

### ISSUE THREAD

**Issue by Mezis4** [MeziTest/QA-51_TeamDiplom#3]
# Описание
Метод `publishGame` в классе `GameStore` добавляет в `store` уже существующую игру

# Локация дефекта
https://github.com/MeziTest/QA-51_TeamDiplom/blob/7c8cf037ffcd6170e4de79d97c7c0c8d80e2cbb8/src/main/java/ru/netology/GameStore.java#L22

# Шаги воспроизведения
1. Открыть [код программы в ветке gamestore](https://github.com/MeziTest/QA-51_TeamDiplom/tree/gamestore) в IDEA и открыть `GameStoreTest`
1. Найти тест `shouldNotAddAlreadyExistentGame`
1. Для строки `Game game = severalGamesStore.publishGame()` выставить: значение параметра `title` "Ведьмак"
1. Выставить значение параметра `genre` "Экшен"
1. Запустить тест
1. В режиме Debug Для теста раскрыть последнюю ветку `severalGamesStore`
1. В ветке раскрыть ячейки игр

*Ожидаемый результат:* В консоли в режиме Debug в ячейках игр ветки `severalGamesStore` нет повторяющихся элементов
*Фактический результат:* В консоли в режиме Debug в ветке `severalGamesStore` отображаются две ячейки с одинаковыми значениями

# Скриншот
![метод publishGame](https://user-images.githubusercontent.com/117623022/215500553-20309d1f-749e-4a22-ac9b-c32e7c9a645d.png)

# Комментарии
Возможно, нужно добавить исключение AlreadyExistsException для метода `publishGame`

# Окружение
* **Операционная система:** Windows 11, версия 21H2
* **IDE:** IntelliJ IDEA 2022.2.4 (Community Edition)
* **Java:** OpenJDK 11

**Comment by andrewturchak78** [comment]
The bug was fixed.
