### ISSUE TITLE
Невозможно получить время, которое игрок играл в игры магазина, из метода addPlayTime

### ISSUE THREAD

**Issue by Mezis4** [MeziTest/QA-51_TeamDiplom#4]
# Описание
Невозможно получить сохраненные часы, проведенные игроком в играх определенного магазина, через метод `addPlayTime`

# Локация дефекта
https://github.com/MeziTest/QA-51_TeamDiplom/blob/7c8cf037ffcd6170e4de79d97c7c0c8d80e2cbb8/src/main/java/ru/netology/GameStore.java#L46

# Шаги воспроизведения
1. Открыть [код программы в ветке gamestore](https://github.com/MeziTest/QA-51_TeamDiplom/tree/gamestore) в IDEA и открыть `GameStoreTest`
1. Найти тест `shouldAccrueHours`
1. Для строки `severalGamesStore.addPlayTime()` выставить: значение параметра `playerName` "Старожил"
1. Выставить значение параметра `hours` "13"
1. Выставить в `int expected` значение 70
1. Выставить в `int actual` значение `getPlayTime("Старожил")`
1. Запустить тест

*Ожидаемый результат:* ожидаемый и фактический результаты совпадают, тест проходит
*Фактический результат:* В консоли отображается ошибка `java: cannot find symbol. symbol: method getPlayTime(java.lang.String)`

# Скриншот
![метод addPlayTime получение Int](https://user-images.githubusercontent.com/117623022/215504972-6fe7fbe6-2fee-4c25-a048-178314395afb.png)

# Комментарии
Возможно, нужно добавить геттер для метода `addPlayTime` или переписать метод для возвращения int-значения через `return`

# Окружение
* **Операционная система:** Windows 11, версия 21H2
* **IDE:** IntelliJ IDEA 2022.2.4 (Community Edition)
* **Java:** OpenJDK 11

**Comment by andrewturchak78** [comment]
The bug was fixed.
