### ISSUE TITLE
Метод addPlayTime не суммирует часы в играх магазина для игрока

### ISSUE THREAD

**Issue by Mezis4** [MeziTest/QA-51_TeamDiplom#5]
# Описание
Метод `addPlayTime` не суммирует ранее наигранные игроком часы в определенном store с новыми часами

# Локация дефекта
https://github.com/MeziTest/QA-51_TeamDiplom/blob/7c8cf037ffcd6170e4de79d97c7c0c8d80e2cbb8/src/main/java/ru/netology/GameStore.java#L46

# Шаги воспроизведения
1. Открыть [код программы в ветке gamestore](https://github.com/MeziTest/QA-51_TeamDiplom/tree/gamestore) в IDEA и открыть `GameStoreTest`
1. Найти тест `shouldFindBestPlayerAmongEqualHours`
1. Для строки `severalGamesStore.addPlayTime()` выставить: значение параметра `playerName` "Кратос"
1. Выставить значение параметра `hours` 40
1. Выставить в `String expected` значение "Старожил"
1. Выставить в `String actual` значение `severalGamesStore.getMostPlayer()`
1. Запустить тест

*Ожидаемый результат:* в методе `addPlayTime` для игрока "Кратос" значение `hours` суммируется с ранее наигранными часами. В консоли в режиме Debug после выполнения метода `addPlayTime` в последней ветке `severalGameStore` в разделе `playedTime` для ячейки "Кратос" в разделе `value` отображается 57

*Фактический результат:* метод `addPlayTime` не суммирует наигранное ранее время и новое значение времени для игрока "Кратос". В консоли в режиме Debug после выполнения метода `addPlayTime` в последней ветке `severalGameStore` в разделе `playedTime` в ячейке "Кратос" в разделе `value` отображается 17 (прежнее наигранное время)

# Скриншот
![метод addPlayTime ДО](https://user-images.githubusercontent.com/117623022/215512965-d67da84b-52a2-4f84-9596-50fb27a46c23.png)

![метод addPlayTIme добавляем](https://user-images.githubusercontent.com/117623022/215513066-e9e08edc-ce1a-4a10-821e-5e1312e618f9.png)

![метод addPlayTime После](https://user-images.githubusercontent.com/117623022/215513104-d82edad9-90a8-4819-be47-aaeab56dbd17.png)

# Окружение
* **Операционная система:** Windows 11, версия 21H2
* **IDE:** IntelliJ IDEA 2022.2.4 (Community Edition)
* **Java:** OpenJDK 11

**Comment by andrewturchak78** [comment]
The bug was fixed.
