### ISSUE TITLE
Не реализован метод getSumPlayedTime

### ISSUE THREAD

**Issue by Mezis4** [MeziTest/QA-51_TeamDiplom#7]
# Описание
Метод `getSumPlayedTime` не прописан по ТЗ: возвращает 0, а не общее количество времени всех игроков, проведённого за играми этого каталога.

# Локация дефекта
https://github.com/MeziTest/QA-51_TeamDiplom/blob/7c8cf037ffcd6170e4de79d97c7c0c8d80e2cbb8/src/main/java/ru/netology/GameStore.java#L75

# Шаги воспроизведения
1. Открыть [код программы в ветке gamestore](https://github.com/MeziTest/QA-51_TeamDiplom/tree/gamestore) в IDEA и открыть `GameStoreTest`
1. Найти тест `shouldCountSumInOnePlayerStore`
1. Выставить в `int expected` значение 15
1. Выставить в `int actual` значение `oneGameStore.getSumPlayedTime()`
1. Запустить тест

*Ожидаемый результат:* expected совпадает с actual, тест проходит. Сумма всех наигранных часов в определенном магазине равняется 15.

*Фактический результат:* expected не совпадает с actual, тест не проходит. Сумма всех наигранных часов в определенном магазине равняется 0.

# Скриншот
![getSum](https://user-images.githubusercontent.com/117623022/215520277-1ab03c1f-9674-45d2-8ea8-3b85641c778d.png)

![метод getSumPlayedTime](https://user-images.githubusercontent.com/117623022/215519241-4447b9f1-8210-48f9-9744-e4d1bb68dc6a.png)

# Окружение
* **Операционная система:** Windows 11, версия 21H2
* **IDE:** IntelliJ IDEA 2022.2.4 (Community Edition)
* **Java:** OpenJDK 11

**Comment by andrewturchak78** [comment]
The bug was fixed.
